version: '3.9'

services:
  transmission:
    container_name: transmission
    image: ghcr.io/linuxserver/transmission
    ports:
      - 9091:9091
      - 51413:51413/udp
      - 51413:51413
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    volumes:
      - /data/transmission/data:/config:rw
      - /data/transmission/downloads:/downloads:rw
      - /data/transmission/watch:/watch:rw
    environment:
      - USER=admin
      - PASS=password
      - TZ=Asia/Kuching
      - PUID=1026
      - PGID=100